from collections.abc import (
    Iterator,
    Container,
    Sized,
    Iterable,
    Sequence,
    MutableSequence,
    Mapping,
    MutableMapping,
    Set,
    MutableSet
)

from typing import (
    TypeVar,
    Generic,
)

K = TypeVar("K")
V = TypeVar("V")
T = TypeVar("T")

class defaultdict(dict[K, V], MutableMapping[K, V]):
    def __missing__(self, key: K) -> V: ...

class deque(Generic[T]):
    def __init__(self, iterable: Iterable[T] = None): ...
    def append(self, x: T) -> None: ...
    def appendleft(self, x: T) -> None: ...
    def pop(self) -> T: ...
    def popleft(self) -> T: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...

class Counter(dict[T, int]):
    def __init__(self, iterable: Iterable[T] = None) -> None: ...
    def elements(self) -> Iterator[T]: ...
    def most_common(self) -> list[tuple[T, int]]: ...

class OrderedDict(dict[K, V], MutableMapping[K, V]):
    def __reversed__(self) -> Iterator[K]: ...
    def move_to_end(self, key: K) -> None: ...
