from __future__ import annotations

from typing import (
    TypeVar,
    Generic,
)

T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")

class Iterator(Generic[T]):
    def __iter__(self) -> Iterator[T]: ...
    def __next__(self) -> T: ...

class Container(Generic[T]):
    def __contains__(self) -> bool: ...

class Sized:
    def __len__(self) -> int: ...

class Iterable(Generic[T]):
    def __iter__(self) -> Iterator[T]: ...

class Sequence(Iterable[T], Sized, Container[T]):
    def __getitem__(self, i: int) -> T: ...
    def __contains__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...

class MutableSequence(Sequence[T]):
    def __setitem__(self, i: int, v: T) -> None: ...
    def __delitem__(self, i: int) -> None: ...
    def insert(self, i: int, v: T) -> None: ...

class Mapping(Generic[K, V]):
    def __getitem__(self, k: K) -> V: ...
    def keys(self) -> Iterable[K]: ...
    def values(self) -> Iterable[V]: ...
    def items(self) -> Iterable[tuple[K, V]]: ...

class MutableMapping(Mapping[K, V]):
    def __setitem__(self, k: K, v: V) -> None: ...
    def __delitem__(self, k: K) -> None: ...

class Set(Generic[T]):
    def __contains__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...

class MutableSet(Set[T]):
    def add(self, v: T) -> None: ...
    def discard(self, v: T) -> None: ...