import typing as _typing
import types as _types
import collections.abc as _abc

_T1 = _typing.TypeVar('_T1')
_T2 = _typing.TypeVar('_T2')
_T = _typing.TypeVar('_T')
_S = _typing.TypeVar('_S')
_K = _typing.TypeVar('_K')
_V = _typing.TypeVar('_V')
_Ts = _typing.TypeVarTuple('_Ts')

class object:
	def __init__(self) -> None: ...
	def __new__(cls, *args, **kwargs) -> type: ...
	def __str__(self) -> str: ...
	def __repr__(self) -> str: ...
	def __eq__(self) -> bool: ...
	def __hash__(self) -> int: ...

class NoneType: ...
class ellipsis: ...
class _NotImplemented: ...

NotImplemented = _NotImplemented()
Ellipsis = ellipsis()

class super: ...
class function: ...
class module: ...

class int:
	def __add__(self) -> int: ...
	def __sub__(self) -> int: ...
	def __mul__(self) -> int: ...
	def __floordiv__(self) -> int: ...
	def __truediv__(self) -> float: ...
	def __mod__(self) -> int: ...
	def __pow__(self) -> int: ...
	def __eq__(self) -> bool: ...
	def __lt__(self) -> bool: ...
	def __le__(self) -> bool: ...
	def __gt__(self) -> bool: ...
	def __ge__(self) -> bool: ...
	def __neg__(self) -> int: ...
	def __abs__(self) -> int: ...
	def __repr__(self) -> str: ...
	def __str__(self) -> str: ...
	def bit_length(self) -> int: ...
	def to_bytes(self) -> bytes: ...
	
	@staticmethod
	def from_bytes() -> int: ...

class bool(int): ...

class float:
	def __add__(self) -> float: ...
	def __sub__(self) -> float: ...
	def __mul__(self) -> float: ...
	def __truediv__(self) -> float: ...
	def __floordiv__(self) -> float: ...
	def __mod__(self) -> float: ...
	def __pow__(self) -> float: ...
	def __eq__(self) -> bool: ...
	def __lt__(self) -> bool: ...
	def __le__(self) -> bool: ...
	def __gt__(self) -> bool: ...
	def __ge__(self) -> bool: ...
	def __neg__(self) -> float: ...
	def __abs__(self) -> float: ...
	def __repr__(self) -> str: ...
	def __str__(self) -> str: ...
	def is_integer(self) -> bool: ...
	def hex(self) -> str: ...
	
	@staticmethod
	def fromhex() -> float: ...

class str(_abc.Iterable[str]):
	def __new__(cls) -> str: ...
	def __add__(self) -> str: ...
	def __mul__(self) -> str: ...
	def __contains__(self) -> bool: ...
	def __eq__(self) -> bool: ...
	def __lt__(self) -> bool: ...
	def __le__(self) -> bool: ...
	def __gt__(self) -> bool: ...
	def __ge__(self) -> bool: ...
	def __getitem__(self) -> str: ...
	def __len__(self) -> int: ...
	def __repr__(self) -> str: ...
	def __str__(self) -> str: ...
	def capitalize(self) -> str: ...
	def casefold(self) -> str: ...
	def center(self) -> str: ...
	def count(self) -> int: ...
	def encode(self) -> bytes: ...
	def endswith(self) -> bool: ...
	def find(self) -> int: ...
	def format(self) -> str: ...
	def isalpha(self) -> bool: ...
	def isdigit(self) -> bool: ...
	def join(self) -> str: ...
	def lower(self) -> str: ...
	def replace(self) -> str: ...
	def split(self) -> list[str]: ...
	def startswith(self) -> bool: ...
	def strip(self) -> str: ...
	def upper(self) -> str: ...

class type(_typing.Generic[_T]):
	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...

	def __init__(self, obj: _T) -> None: ...

class list(_abc.MutableSequence[_T]):
	def __init__(self, value: _abc.Iterable[_T]) -> None: ...

	@classmethod
	def __class_getitem__(cls) -> _types.GenericAlias: ...

	def __len__(self) -> int: ...
	def __iter__(self) -> _abc.Iterator[_T]: ...
	def __getitem__(self, index) -> _T: ...
	def __setitem__(self, index, value: _T) -> None: ...
	def __delitem__(self, index) -> None: ...
	def __contains__(self) -> bool: ...
	def __add__(self, other: _abc.Iterable[_T]) -> list[_T]: ...
	def __iadd__(self, other: _abc.Iterable[_T]) -> list[_T]: ...
	def __mul__(self) -> list[_T]: ...
	def __rmul__(self) -> list[_T]: ...
	def __imul__(self) -> list[_T]: ...
	def append(self, item: _T) -> None: ...
	def extend(self, iterable: _abc.Iterable[_T]) -> None: ...
	def insert(self, index, item: _T) -> None: ...
	def remove(self, item: _T) -> None: ...
	def pop(self) -> _T: ...
	def clear(self) -> None: ...
	def index(self, item: _T) -> int: ...
	def count(self, item: _T) -> int: ...
	def sort(self) -> None: ...
	def reverse(self) -> None: ...
	def copy(self) -> list[_T]: ...
	
class set(_abc.MutableSet[_T]):

	# def __init__(self, value: _abc.Iterable[_T]) -> None: ...

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...

	def __len__(self) -> int: ...
	def __iter__(self) -> _abc.Iterator[_T]: ...
	def __contains__(self, element: _T) -> bool: ...

	def __eq__(self) -> bool: ...
	def __ne__(self) -> bool: ...
	def __lt__(self, other: _abc.Set[_T]) -> bool: ...
	def __le__(self, other: _abc.Set[_T]) -> bool: ...
	def __gt__(self, other: _abc.Set[_T]) -> bool: ...
	def __ge__(self, other: _abc.Set[_T]) -> bool: ...

	def __or__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __and__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __sub__(self, other: _abc.Set[_S]) -> set[_T]: ...
	def __xor__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...

	def __ror__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __rand__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __rsub__(self, other: _abc.Set[_S]) -> set[_S]: ...
	def __rxor__(self, other: _abc.Set[_S]) -> set[_typing.Union[_T, _S]]: ...

	def __ior__(self, other: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __iand__(self, other: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...
	def __isub__(self, other: _abc.Iterable[_S]) -> set[_T]: ...
	def __ixor__(self, other: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...

	def add(self, element: _T) -> None: ...
	def clear(self) -> None: ...
	def copy(self) -> set[_T]: ...
	def discard(self, element: _T) -> None: ...
	def pop(self) -> _T: ...
	def remove(self, element: _T) -> None: ...
	def update(self, *others: _abc.Iterable[_S]) -> None: ...
	def intersection_update(self, *others: _abc.Iterable[_S]) -> None: ...
	def difference_update(self, *others: _abc.Iterable[_S]) -> None: ...
	def symmetric_difference_update(self, other: _abc.Iterable[_S]) -> None: ...

	def union(self, *others: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...
	def intersection(self, *others: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...
	def difference(self, *others: _abc.Iterable[_S]) -> set[_T]: ...
	def symmetric_difference(self, other: _abc.Iterable[_S]) -> set[_typing.Union[_T, _S]]: ...

	def isdisjoint(self, other: _abc.Iterable[object]) -> bool: ...
	def issubset(self, other: _abc.Iterable[object]) -> bool: ...
	def issuperset(self, other: _abc.Iterable[object]) -> bool: ...
	
class dict(_abc.MutableMapping[_K, _V]):

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
	def __len__(self) -> int: ...
	def __getitem__(self, key: _K) -> _V: ...
	def __setitem__(self, key: _K, value: _V) -> None: ...
	def __delitem__(self, key: _K) -> None: ...
	def __iter__(self) -> _abc.Iterator[_K]: ...
	def __eq__(self, value: object) -> bool: ...
	def __reversed__(self) -> _abc.Iterator[_K]: ...
	def __or__(self, value: dict[_T1, _T2]) -> dict[_typing.Union[_K, _T1], _typing.Union[_V, _T2]]: ...
	def __ror__(self, value: dict[_T1, _T2]) -> dict[_typing.Union[_K, _T1], _typing.Union[_V, _T2]]: ...

	def copy(self) -> dict[_K, _V]: ...
	def keys(self) -> _abc.Iterator[_K]: ...
	def values(self) -> _abc.Iterator[_V]: ...
	def items(self) -> _abc.Iterator[tuple[_K, _V]]: ...

	def fromkeys(cls, iterable: _abc.Iterable[_T], value: _S) -> dict[_T, _S]: ...
	def get(self, key: _K, default: _T) -> _typing.Union[_V, _T]: ...
	def pop(self, key: _K, default: _T) -> _typing.Union[_V, _T]: ...
	
class frozenset(_abc.Iterable[_T]): 

	def __init__(self, value: _abc.Iterable[_T]) -> None: ...

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class tuple(_abc.Iterable, _typing.Generic[_typing.Unpack[_Ts]]): 

	@classmethod
	def __class_getitem__(cls, item) -> _types.GenericAlias: ...
	
class complex: ...
class bytes: ...
class bytearray: ...
class memoryview: ...
class range: ...
class slice: ...
class property: ...
class staticmethod: ...
class classmethod: ...

class BaseException: ...
class Exception: ...
class ValueError: ...
class TypeError: ...
class AttributeError: ...
class NameError: ...
class KeyError: ...
class IndexError: ...
class ImportError: ...
class RuntimeError: ...
class NotImplementedError: ...
class StopIteration: ...
class StopAsyncIteration: ...
class GeneratorExit: ...
class SystemExit: ...
class OSError: ...

def len() -> int: ...
def print() -> None: ...
def input() -> str: ...
def isinstance() -> bool: ...
def issubclass() -> bool: ...
def id() -> int: ...
def open() -> _types.Any: ...
def abs() -> _types.Any: ...
def min() -> _types.Any: ...
def max() -> _types.Any: ...
def sum() -> _types.Any: ...
def all() -> bool: ...
def any() -> bool: ...
def dir() -> list[str]: ...
def repr(obj) -> str: return obj.__repr__()
def hasattr() -> bool: ...
def getattr() -> _types.Any: ...
def setattr() -> None: ...
def delattr() -> None: ...
def globals() -> dict[str, _types.Any]: ...
def locals() -> dict[str, _types.Any]: ...
def vars() -> dict[str, _types.Any]: ...
def callable() -> bool: ...
def iter() -> _types.Any: ...
def next() -> _types.Any: ...
def eval() -> _types.Any: ...
def exec() -> None: ...
def compile() -> _types.Any: ...
def format() -> str: ...
def hash() -> int: ...
def help() -> None: ...
def ord() -> int: ...
def chr() -> str: ...
def bin() -> str: ...
def oct() -> str: ...
def hex() -> str: ...
def sorted() -> list[_types.Any]: ...
def reversed() -> _types.Any: ...
def enumerate() -> _types.Any: ...
def zip() -> _types.Any: ...
def map() -> _types.Any: ...
def filter() -> _types.Any: ...
def pow() -> _types.Any: ...
def round() -> _types.Any: ...
def divmod() -> tuple[_types.Any, _types.Any]: ...
def exit() -> None: ...
def quit() -> None: ...
def breakpoint() -> None: ...